fixed arg --repair and used first git.linux-gaming.ru

diff --git a/portproton b/portproton
--- a/portproton
+++ b/portproton
@@ -138,7 +138,6 @@ if [[ "$1" != "--repair" ]] ; then
 			"$loc_other_path")
 				D_PATH="$($yad_gui --file --directory --title="$loc_set_path" --width=800 --height=800)" ;;
 		esac
-
 		[[ -z "${D_PATH}" ]] && fatal
 		echo "${D_PATH}" | grep -i "PortProton" 2>/dev/null || D_PATH="${D_PATH}/PortProton"
 		export PORT_WINE_DATA_PATH="${D_PATH}/data"
@@ -156,10 +155,19 @@ fi
 if [[ ! -d "${PORT_WINE_DATA_PATH}" ]] ; then
     mkdir -p "$PORT_WINE_DATA_PATH" || fatal "Cannot create a directory: $PORT_WINE_PATH"
 elif [[ "$1" == "--repair" ]] ; then
-	rm -f "${PORT_WINE_DATA_PATH}/scripts/"* 2>/dev/null
+	rm -fr "${PORT_WINE_DATA_PATH}/tmp"/{cache_lang,gstreamer_tmp}/
+	rm -f "${PORT_WINE_DATA_PATH}/tmp"/{scripts_ver,fixes_apply,update_skip_mirror}
+	rm -f "${PORT_WINE_DATA_PATH}/tmp"/{scripts_update_notifier,update_remind_later}
 else
-	rm -fr "${PORT_WINE_DATA_PATH}/tmp"
-	rm -f "${PORT_WINE_DATA_PATH}/scripts/"* 2>/dev/null
+	rm -fr "${PORT_WINE_DATA_PATH}/tmp/"
+	rm -fr "${PORT_WINE_DATA_PATH}/dist/"
+fi
+rm -fr "${PORT_WINE_DATA_PATH}/img/"
+rm -fr "${PORT_WINE_DATA_PATH}/locales/"
+rm -fr "${PORT_WINE_DATA_PATH}/scripts/"
+if [[ -f "${PORT_WINE_DATA_PATH}/user.conf" ]] ; then
+	echo "WARNING: Moved your user.conf to user.conf.bak"
+	mv "${PORT_WINE_DATA_PATH}/user.conf" "${PORT_WINE_DATA_PATH}/user.conf.bak"
 fi
 ########################################################################
 mkdir -p "${PORT_WINE_DATA_PATH}/tmp"
@@ -180,25 +188,35 @@ $yad_gui --progress --pulsate --title="$loc_install" --text="$loc_install" \
 		 --close-on-unfocus --no-buttons --skip-taskbar --width=500 &>/dev/null &
 sleep 1
 
-echo -e "\nTry download scripts from gitlab.eterfund.ru..."
+echo -e "Try download scripts from git.linux-gaming.ru..."
 if ! curl -f -# -A "Mozilla/5.0 (compatible; Konqueror/2.1.1; X11)" -H 'Cache-Control: no-cache, no-store' -H 'Pragma: no-cache' \
-	-L "https://gitlab.eterfund.ru/Castro-Fidel/PortWINE/-/archive/master/PortWINE-master.tar.gz" \
-	-o "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz"
+		-L "https://git.linux-gaming.ru/CastroFidel/PortWINE/archive/master.tar.gz" \
+		-o "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz"
 then
-	echo -e "\nError.\nTry download scripts from github.com..."
-	curl -f -# -A "Mozilla/5.0 (compatible; Konqueror/2.1.1; X11)" -H 'Cache-Control: no-cache, no-store' -H 'Pragma: no-cache' \
-	-L "https://github.com/Castro-Fidel/PortWINE/archive/refs/heads/master.tar.gz" \
-	-o "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz"
-	[ "$?" != "0" ] && fatal "Critical error during file download!"
+	echo -e "\nError.\nTry download scripts from gitlab.eterfund.ru..."
+	if ! curl -f -# -A "Mozilla/5.0 (compatible; Konqueror/2.1.1; X11)" -H 'Cache-Control: no-cache, no-store' -H 'Pragma: no-cache' \
+		-L "https://gitlab.eterfund.ru/Castro-Fidel/PortWINE/-/archive/master/PortWINE-master.tar.gz" \
+		-o "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz"
+	then
+		echo -e "\nError.\nTry download scripts from github.com..."
+		curl -f -# -A "Mozilla/5.0 (compatible; Konqueror/2.1.1; X11)" -H 'Cache-Control: no-cache, no-store' -H 'Pragma: no-cache' \
+		-L "https://github.com/Castro-Fidel/PortWINE/archive/refs/heads/master.tar.gz" \
+		-o "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz"
+		[ "$?" != "0" ] && fatal "Critical error during file download!"
+	fi
 fi
-
 echo "Try unpacking scripts..."
-tar -xvzf "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz" -C "${PORT_WINE_TMP_PATH}"
+tar -xzf "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz" -C "${PORT_WINE_TMP_PATH}"
 if [ "$?" = "0" ] ; then
 	[ ! -d "${PORT_WINE_DATA_PATH}" ] && mkdir "${PORT_WINE_DATA_PATH}"
-	cp -fr "${PORT_WINE_TMP_PATH}/PortWINE-master/data_from_portwine/"* "${PORT_WINE_DATA_PATH}"
+	if [[ "${PORT_WINE_TMP_PATH}/portwine" ]] ; then
+		cp -fr "${PORT_WINE_TMP_PATH}/portwine/data_from_portwine/"* "${PORT_WINE_DATA_PATH}"
+		rm -fr "${PORT_WINE_TMP_PATH}/portwine/"
+	else
+		cp -fr "${PORT_WINE_TMP_PATH}/PortWINE-master/data_from_portwine/"* "${PORT_WINE_DATA_PATH}"
+		rm -fr "${PORT_WINE_TMP_PATH}/PortWINE-master/"
+	fi
 	rm -f "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz"
-	rm -fr "${PORT_WINE_TMP_PATH}/PortWINE-master/"
 	export scripts_current_ver=$(cat "${PORT_WINE_DATA_PATH}/scripts/var" | grep SCRIPTS_NEXT_VERSION | awk -F "=" '{print $2}')
 	echo "${scripts_current_ver}" > "${PORT_WINE_TMP_PATH}/scripts_ver"
 else
