Do not download scripts if they are already in the right place

diff --git a/portproton b/portproton
--- a/portproton
+++ b/portproton
@@ -4,7 +4,7 @@
 # License MIT
 ########################################################################
 unset PW_AUTOPLAY PW_SET_LANG PW_SILENT_INSTALL
-export port_ver=1.6.1
+export port_ver=1.6.2
 ########################################################################
 cd "$(dirname "$(readlink -f "$0")")"
 script_path="$(pwd)"
@@ -165,16 +165,18 @@ $yad_gui --progress --pulsate --title="$loc_install" --text="$loc_install" \
 		 --close-on-unfocus --no-buttons --skip-taskbar --width=500 &>/dev/null &
 sleep 1
 
-echo -e "\nTry download scripts from gitlab.eterfund.ru..."
-if ! curl -f -# -A "Mozilla/5.0 (compatible; Konqueror/2.1.1; X11)" -H 'Cache-Control: no-cache, no-store' -H 'Pragma: no-cache' \
-	-L "https://gitlab.eterfund.ru/Castro-Fidel/PortWINE/-/archive/master/PortWINE-master.tar.gz" \
-	-o "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz"
-then
-	echo -e "\nError.\nTry download scripts from github.com..."
-	curl -f -# -A "Mozilla/5.0 (compatible; Konqueror/2.1.1; X11)" -H 'Cache-Control: no-cache, no-store' -H 'Pragma: no-cache' \
-	-L "https://github.com/Castro-Fidel/PortWINE/archive/refs/heads/master.tar.gz" \
-	-o "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz"
-	[ "$?" != "0" ] && fatal "Critical error during file download!"
+if [ ! -f "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz" ] ; then
+	echo -e "\nTry download scripts from gitlab.eterfund.ru..."
+	if ! curl -f -# -A "Mozilla/5.0 (compatible; Konqueror/2.1.1; X11)" -H 'Cache-Control: no-cache, no-store' -H 'Pragma: no-cache' \
+		-L "https://gitlab.eterfund.ru/Castro-Fidel/PortWINE/-/archive/master/PortWINE-master.tar.gz" \
+		-o "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz"
+	then
+		echo -e "\nError.\nTry download scripts from github.com..."
+		curl -f -# -A "Mozilla/5.0 (compatible; Konqueror/2.1.1; X11)" -H 'Cache-Control: no-cache, no-store' -H 'Pragma: no-cache' \
+		-L "https://github.com/Castro-Fidel/PortWINE/archive/refs/heads/master.tar.gz" \
+		-o "${PORT_WINE_TMP_PATH}/PortWINE-master.tar.gz"
+		[ "$?" != "0" ] && fatal "Critical error during file download!"
+	fi
 fi
 
 echo "Try unpacking scripts..."
